add_newline = true

[line_break]
disabled = true

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[git_commit]
tag_disabled = false
tag_symbol = " 🔖 "

[username]
style_user = "bold green"
style_root = "bold red"
format = "[$user]($style) in "
disabled = false
show_always = true
