add_newline = false

[username]
show_always = false
format = '[$user]($style) on '

[git_commit]
tag_disabled = false

[hostname]
ssh_only = true

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold yellow'
symbol = '🅰 '
[aws.profile_aliases]
CompanyGroupFrobozzOnCallAccess = 'Frobozz'

